/*
 * This code is made available under the terms of the Eclipse Public License v1.0
 * in the github project https://github.com/project-husky/husky there you also
 * find a list of the contributors and the license information.
 *
 * This project has been developed further and modified by the joined working group Husky
 * on the basis of the eHealth Connector opensource project from June 28, 2021,
 * whereas medshare GmbH is the initial and main contributor/author of the eHealth Connector.
 */

/**
 * This package contains the APPC document models generated from its XML Schema.
 * <p>
 * This package was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
 * v2.2.8-b130911.1802 See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> Any modifications to
 * this package will be lost upon recompilation of the source schema. Generated on: 2020.03.06 at 06:50:21 PM CET
 * <p>
 * The Schema is published at
 * <a href="https://drive.google.com/drive/folders/13FCw8IJliiVdQFt4bBEmCPW93E5x710R">https://drive.google.com/drive/folders/13FCw8IJliiVdQFt4bBEmCPW93E5x710R</a>
 * <p>
 * The package was generated with the command
 * <code>"C:\Program Files\AdoptOpenJDK\jdk-8\bin\xjc.exe" -p org.husky.appc.models -d
 * husky/husky-appc/husky-appc-gen/src/main/java -enableIntrospection -encoding UTF-8
 * file:/D:/ihe-appc-xacml-combined-schema-1.0.xsd</code>
 *
 * @author Quentin Ligier
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@DefaultQualifier(value = Nullable.class, locations = {TypeUseLocation.PARAMETER, TypeUseLocation.RETURN,
        TypeUseLocation.FIELD})
package org.husky.appc.models;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.framework.qual.DefaultQualifier;
import org.checkerframework.framework.qual.TypeUseLocation;